app:
    resource:   "@AppBundle/Controller/"
    type:       annotation
    
api:
    resource:   "@AppBundle/Controller/"
    type:       annotation

oauth:
    resource:   "@AppBundle/Controller/"
    type:       annotation

fos_oauth_server_token:
    resource:   "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource:   "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

logout:
    path: /logout