# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_provider:
            entity:
                class: AppBundle:User
                property: email
        api_user_provider:
            id: platform.user.provider
    
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:    ^/api
            anonymous: ~
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_user_provider
            stateless:  true
        
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                provider:   user_provider
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /
                
    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(privacy|content|terms)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(register|confirm|suffix|forgot|password), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
